development:
  adapter: postgresql
  encoding: unicode
  database: teacher
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: teacher_test
  pool: 5
  username: teacher
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: teacher_production
  pool: 5
  username: teacher
  password:
